# File: .github/workflows/release.yml

name: 🔖 Release Automation

on:
  push:
    tags:
      - "v*" # Triggers only when pushing tags like v1.0.0, v2.0.1, etc.

jobs:
  create-release:
    name: 📅 Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: 💾 Checkout Repository
        uses: actions/checkout@v4

      - name: 📖 Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true # Automatically generates nice release notes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_RELEASES }}
